name: Post to Mastodon on Release
description: A GitHub Action to post release announcements to Mastodon
author: Christian Meesters

inputs:
  message:
    description: 'The message to post to Mastodon'
    required: true
  access-token:
    description: 'Mastodon access token for authentication'
    required: true
  pr-title:
    description: 'The title of the pull request'
    required: true
  base-url:
    description: 'The base URL of the Mastodon instance'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y python3-mastodon
      shell: bash
      
    - name: Post to Mastodon
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          python3 ${{ github.action_path }}/post_to_mastodon.py \
          --message "${{ inputs.message }}" \
          --access-token "${{ inputs.access-token }}" \
        command: |
          set -o errexit
          args=(
            --message "${{ inputs.message }}"
            --access-token "${{ inputs.access-token }}"
            --pr-title "${{ inputs.pr-title }}"
          )
          if [ -n "${{ inputs.base-url }}" ]; then
            args+=(--base-url "${{ inputs.base-url }}" )
          fi
          python3 "${{ github.action_path }}/post_to_mastodon.py" "${args[@]}"

