name: CI

on:
  push:
    branches: 
        - main
  pull_request:
    branches: [ * ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        run: pip install poetry

      - name: Determine dependencies
        run: poetry lock

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Check formatting
        run: poetry run black --check .
  
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        run: pip install poetry

      - name: Determine dependencies
        run: poetry lock

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Check code
        run: poetry run flake8
        run: poetry run black --check .
    
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry  
      
      - name: Install dependencies
        run: |
          poetry install

      - name: Run pytest
        run: |
          poetry run coverage run -m pytest tests/tests.py -sv --tb=short --disable-warnings
      
      - name: Run Coverage
        run: |
          poetry run coverage report -m